spring.application.name=auth-service

server.port=8001


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/skillswap_auth_service_pg}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Soul2240}


spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update


jwt.secret=${JWT_SECRET:w7JG#83jd!kL2@smF92nCq%9vd8$klfL%9aAaZz@00}
