version: "3.8"

services:
  # =========================
  # GATEWAY (PUERTA DE ENTRADA)
  # =========================
  gateway:
    image: stevenpc/gateway:1.0.0
    container_name: gateway

    ports:
      - "8080:8080"

    depends_on:
      - auth-service
      - user-service

    environment:
      AUTH_SERVICE_URL: http://auth-service:8001
      USER_SERVICE_URL: http://user-service:8002

    networks:
      - micro-net

  # =========================
  # AUTH SERVICE (MICROSERVICIO DE AUTENTICACIÓN)
  # =========================
  auth-service:
    image: stevenpc/auth:1.0.0
    container_name: auth-service

    ports:
      - "8001:8001"

    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      USER_SERVICE_URL: http://user-service:8002  # ✅ AGREGADO

    networks:
      - micro-net

  # =========================
  # USER SERVICE (MICROSERVICIO DE USUARIOS)
  # =========================
  user-service:
    image: stevenpc/user:1.0.0
    container_name: user-service

    ports:
      - "8002:8002"

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

    networks:
      - micro-net

  # =========================
  # POSTGRES (BASE DE DATOS DE AUTH SERVICE)
  # =========================
  postgres:
    image: postgres:15-alpine
    container_name: auth-postgres

    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - micro-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # =========================
  # MYSQL (BASE DE DATOS DE USER SERVICE)
  # =========================
  mysql:
    image: mysql:8
    container_name: user-mysql

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: user_db

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - micro-net

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

# =========================
# RED COMPARTIDA
# =========================
networks:
  micro-net:

# =========================
# VOLUMENES
# =========================
volumes:
  postgres_data:
  mysql_data: