spring.application.name=user-service

server.port=8002

#CONNECTION
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/skillswap_user_service_mysql}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Soul2240}

#DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


auth.service.url=http://localhost:8001
jwt.secret=${JWT_SECRET:w7JG#83jd!kL2@smF92nCq%9vd8$klfL%9aAaZz@00}





